[MFLOG|0|2024-10-19T22:01:42.600952Z|runtime|c8f893dc-b113-4be8-a56a-f468eaffb550]    Internal error
[MFLOG|0|2024-10-19T22:01:42.602284Z|runtime|199c1b62-b82e-4ed2-b49d-dc73f27e0916]Traceback (most recent call last):
[MFLOG|0|2024-10-19T22:01:42.602332Z|runtime|f3d2d4b7-35b4-40f7-bd1b-f8625d9952cc]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/cli.py", line 1139, in main
[MFLOG|0|2024-10-19T22:01:42.602369Z|runtime|a7a33602-68b1-4c65-9b4f-c330202951cd]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2024-10-19T22:01:42.602417Z|runtime|a179d4e5-9414-4fd0-8fe4-99117dd49eda]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2024-10-19T22:01:42.602454Z|runtime|855f951f-2944-456f-bf8b-cd227234f0a3]    return func(args, kwargs)
[MFLOG|0|2024-10-19T22:01:43.124408Z|runtime|0eb51f7d-9431-46bd-b891-a43dfcaa463e]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.124636Z|runtime|0117cd05-0809-4dd1-85df-1f10cc512d43]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2024-10-19T22:01:43.124677Z|runtime|c968549d-7017-4b6b-a27d-c267483669c5]    return self.main(args, kwargs)
[MFLOG|0|2024-10-19T22:01:43.124703Z|runtime|b7055fdb-47aa-4cdb-a244-5cf3010fa412]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.124727Z|runtime|0aa30693-cfdd-4807-845b-53d5406d090f]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2024-10-19T22:01:43.124748Z|runtime|be477624-3c82-4039-9f52-e511d6630b5a]    rv = self.invoke(ctx)
[MFLOG|0|2024-10-19T22:01:43.124769Z|runtime|722f60f9-6bc6-4f78-9a98-214f3cee26c1]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.124790Z|runtime|6e8d1473-c263-4175-a7eb-e992b10e0cbe]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2024-10-19T22:01:43.124808Z|runtime|e509ceaa-1bb1-4d3c-aa44-73f2dbd4cd8c]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2024-10-19T22:01:43.124829Z|runtime|fd828772-00e8-4cb4-838f-407159718d84]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.124849Z|runtime|0ff3da3d-1a66-4df2-b490-b3152fd3f68d]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2024-10-19T22:01:43.124867Z|runtime|2e633f25-b071-46db-a91d-541518ed0960]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2024-10-19T22:01:43.124884Z|runtime|4ce32eaf-c18a-46fd-bca0-a382502b98be]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.124905Z|runtime|9707edf7-6c91-47d7-b8c5-8fc05b5ec1ef]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2024-10-19T22:01:43.124923Z|runtime|3df65166-e4c8-4fa5-81bf-02e303cf8b62]    return callback(args, kwargs)
[MFLOG|0|2024-10-19T22:01:43.124941Z|runtime|f8e52907-06f7-4c1c-81ba-138774691475]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.124961Z|runtime|e04936a1-5ed4-44b8-8a52-dc89157b1be1]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2024-10-19T22:01:43.124984Z|runtime|f69ae01b-0d8e-426b-8edd-44757ccf3be8]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2024-10-19T22:01:43.125000Z|runtime|830bcb6b-ceec-41e7-860f-3841e29f211d]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.125018Z|runtime|3bb378ed-aa67-4a6c-90e2-0d1bff2fa9df]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/cli.py", line 469, in step
[MFLOG|0|2024-10-19T22:01:43.125035Z|runtime|8952e3b8-8324-499e-a56a-246a24a57720]    task.run_step(
[MFLOG|0|2024-10-19T22:01:43.125055Z|runtime|9cf037b1-142d-4da0-b7bf-722935b9e1ab]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/task.py", line 729, in run_step
[MFLOG|0|2024-10-19T22:01:43.125072Z|runtime|f17bd200-eed4-4d72-aab1-c17ec88f725c]    output.persist(self.flow)
[MFLOG|0|2024-10-19T22:01:43.125092Z|runtime|ec1fa5f6-6aa1-4067-8dff-884cb6ada5e8]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 31, in method
[MFLOG|0|2024-10-19T22:01:43.125112Z|runtime|cb3c0dcc-9b55-43c1-ae6c-5ac80ac58b1d]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T22:01:43.125130Z|runtime|c2fb604e-4af0-4195-8549-ab743ad3383f]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.125147Z|runtime|f2d63760-03a5-486b-9945-9fc0195b7af3]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 45, in method
[MFLOG|0|2024-10-19T22:01:43.125164Z|runtime|d55e99c6-da36-488a-9d8d-92471eecf974]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T22:01:43.125184Z|runtime|6fe173de-ed2e-40fc-aeaa-3ba1d4a78daf]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.125200Z|runtime|49daeecb-4c25-4cc1-a763-9c7da142adc7]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 744, in persist
[MFLOG|0|2024-10-19T22:01:43.125217Z|runtime|c21ba2df-a6bc-4c2e-ac50-cb3ba7351486]    self.save_artifacts(artifacts_iter(), len_hint=len(valid_artifacts))
[MFLOG|0|2024-10-19T22:01:43.125236Z|runtime|4a3dfd81-9260-4503-b41d-39355bd57001]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 31, in method
[MFLOG|0|2024-10-19T22:01:43.125253Z|runtime|460e4334-7d94-453a-a0c6-1f77c956c3d3]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T22:01:43.125272Z|runtime|83969d86-b4a5-4406-84d7-60098d23b23c]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.125289Z|runtime|0791cf2b-fa35-4d7a-928f-f208975d88a3]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 45, in method
[MFLOG|0|2024-10-19T22:01:43.125311Z|runtime|b654ee5f-5f30-4dff-b47a-5813dffa4936]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T22:01:43.125327Z|runtime|9ad6f770-ab14-4fdb-b00f-e8593b1c314a]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.125347Z|runtime|9f9371f4-c80c-47d7-a745-220724efc033]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 329, in save_artifacts
[MFLOG|0|2024-10-19T22:01:43.125366Z|runtime|b6cd2645-e915-4b98-9903-48cd650cd814]    save_result = self._ca_store.save_blobs(pickle_iter(), len_hint=len_hint)
[MFLOG|0|2024-10-19T22:01:43.125386Z|runtime|57e70090-1b8b-40ae-b30a-94947cfa17e6]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.125403Z|runtime|2fff2745-8e3b-4af5-90b1-8892b4dc4e0b]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/content_addressed_store.py", line 100, in save_blobs
[MFLOG|0|2024-10-19T22:01:43.125419Z|runtime|3629973c-5973-4781-a431-3b80164dfb24]    self._storage_impl.save_bytes(packing_iter(), overwrite=True, len_hint=len_hint)
[MFLOG|0|2024-10-19T22:01:43.125436Z|runtime|c850b24d-b990-47a3-94b7-9b768feb600a]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/plugins/datastores/local_storage.py", line 107, in save_bytes
[MFLOG|0|2024-10-19T22:01:43.125453Z|runtime|48423132-60f4-442d-9128-f2dbf284b31d]    for path, obj in path_and_bytes_iter:
[MFLOG|0|2024-10-19T22:01:43.125470Z|runtime|483def0b-0550-4b66-8e16-7658f6064d24]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/content_addressed_store.py", line 78, in packing_iter
[MFLOG|0|2024-10-19T22:01:43.125487Z|runtime|8a2438d0-734a-44b2-b740-2cd24b64e725]    for blob in blob_iter:
[MFLOG|0|2024-10-19T22:01:43.125504Z|runtime|0a1dc882-cab6-457c-9ea8-41e4303f5f0c]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 302, in pickle_iter
[MFLOG|0|2024-10-19T22:01:43.125522Z|runtime|1f93404e-4c68-4e9a-bae4-fc02ffbd648c]    blob = pickle.dumps(obj, protocol=2)
[MFLOG|0|2024-10-19T22:01:43.125538Z|runtime|c25b9f0b-cf36-4361-9c8e-28587b353f27]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.125555Z|runtime|0c32b070-f64d-404f-9970-c53c0a671d18]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/tensorflow/python/framework/ops.py", line 327, in __reduce__
[MFLOG|0|2024-10-19T22:01:43.125572Z|runtime|39bf6036-0ea4-40fe-b2b4-7f48222765b9]    return convert_to_tensor, (self._numpy(),)
[MFLOG|0|2024-10-19T22:01:43.125592Z|runtime|7ab5fcb3-1b1d-4ce0-94a1-cc8d7af06928]                               ^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.125609Z|runtime|a2821b65-1cfa-4441-8725-d50eb3f78c07]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/tensorflow/python/framework/ops.py", line 375, in _numpy
[MFLOG|0|2024-10-19T22:01:43.125626Z|runtime|a9b1f67b-955d-4159-bb4b-7f58e82010c1]    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
[MFLOG|0|2024-10-19T22:01:43.125643Z|runtime|3be99982-fbc4-4b60-86eb-824b31b2aa60]    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T22:01:43.125660Z|runtime|64791bf4-11e0-4de8-bba8-944c43786749]tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot convert a Tensor of dtype variant to a NumPy array.
[MFLOG|0|2024-10-19T22:01:43.125677Z|runtime|4bc3147a-9981-4da8-9d98-4d702ae339b0]
[MFLOG|0|2024-10-19T22:01:43.126211Z|runtime|374b7efc-b38d-4477-bf82-01c3d7b8e611]Task failed.