[MFLOG|0|2024-10-19T21:58:34.662503Z|runtime|44c00eb3-d123-4e2f-af04-4a4ff1b7a70a]    Internal error
[MFLOG|0|2024-10-19T21:58:34.663931Z|runtime|643dffc7-9b28-439d-bf9c-e0c050029cce]Traceback (most recent call last):
[MFLOG|0|2024-10-19T21:58:34.663992Z|runtime|0ac4626e-58b5-4cba-b872-d87c5674aad4]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/cli.py", line 1139, in main
[MFLOG|0|2024-10-19T21:58:34.664023Z|runtime|856ad4f5-dbd2-4d17-a6d9-247097f43aea]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2024-10-19T21:58:34.664066Z|runtime|4b5faa03-39c9-4c21-a547-d64e0f348673]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2024-10-19T21:58:34.664098Z|runtime|9bf1230b-befc-4055-9d43-e3e0404666e6]    return func(args, kwargs)
[MFLOG|0|2024-10-19T21:58:35.250751Z|runtime|cbfefc19-168d-4322-a104-4b2eede1d4f0]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.250970Z|runtime|fb143912-e6c9-44a1-b48b-35381e0edc9e]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2024-10-19T21:58:35.251012Z|runtime|248bd62c-9e7b-4bd0-a1da-3e56c952aa4d]    return self.main(args, kwargs)
[MFLOG|0|2024-10-19T21:58:35.251039Z|runtime|d274f437-1b7a-4f7b-86ae-2af53d0169ce]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251068Z|runtime|e05977bb-82ee-4d19-811a-947f9c5b0431]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2024-10-19T21:58:35.251090Z|runtime|db6aa20a-1d08-4013-8d85-a26fa9d9cd2a]    rv = self.invoke(ctx)
[MFLOG|0|2024-10-19T21:58:35.251109Z|runtime|abe82db2-cad4-4006-98b2-ca772a34a2f5]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251149Z|runtime|f39c45cc-e5f8-4b7a-9d4e-35f22c5a7fe9]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2024-10-19T21:58:35.251168Z|runtime|ea8fe534-f9ba-4874-960a-da185ba0456a]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2024-10-19T21:58:35.251187Z|runtime|65e8511e-8279-49d9-98a3-eb506d6c485e]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251214Z|runtime|556876e5-b160-4f5a-be4b-40d1714b18ad]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2024-10-19T21:58:35.251236Z|runtime|3dcb0cf4-89ec-4635-9fc3-73f7e22dc52c]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2024-10-19T21:58:35.251256Z|runtime|aba9a74a-e740-466e-a0de-e8399f317306]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251275Z|runtime|ba217eba-90a8-4ad0-93d9-1572f2dcb279]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2024-10-19T21:58:35.251297Z|runtime|e2ae5ec4-da61-4545-8014-9d8724e00a10]    return callback(args, kwargs)
[MFLOG|0|2024-10-19T21:58:35.251319Z|runtime|5c8ac5a2-d2c1-4263-8e84-fdc984cd4817]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251338Z|runtime|22c80bac-3a8c-42ee-8d97-43de29ec2b09]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2024-10-19T21:58:35.251356Z|runtime|4ce36800-e779-42e3-8bad-c9b5e51d013a]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2024-10-19T21:58:35.251375Z|runtime|c2f1872e-d501-45ee-a74f-50ecbe9fd591]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251393Z|runtime|b3baaf2a-a631-4f5b-8072-12f4fa23a2e4]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/cli.py", line 469, in step
[MFLOG|0|2024-10-19T21:58:35.251411Z|runtime|5525ca10-06ed-4c5d-bfed-a682a8077f89]    task.run_step(
[MFLOG|0|2024-10-19T21:58:35.251428Z|runtime|8cab44a3-1f20-4f44-a419-68b59d2098b0]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/task.py", line 729, in run_step
[MFLOG|0|2024-10-19T21:58:35.251445Z|runtime|8c0f280e-7b4e-4bf4-b515-153df63548ac]    output.persist(self.flow)
[MFLOG|0|2024-10-19T21:58:35.251461Z|runtime|e79f5a93-2c82-4cab-9edb-5807e6943898]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 31, in method
[MFLOG|0|2024-10-19T21:58:35.251484Z|runtime|37a4c4b9-1088-4135-bbc8-58b11b5329ad]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T21:58:35.251503Z|runtime|ffe5abb9-2751-4377-a008-0db52f14c9ee]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251520Z|runtime|8df529f4-7e83-45d5-8770-9655315bc47b]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 45, in method
[MFLOG|0|2024-10-19T21:58:35.251540Z|runtime|400013cc-3bac-45b1-bbad-0ad690bc33ac]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T21:58:35.251558Z|runtime|f4c5e260-da1b-4083-83d4-978ffc225728]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251577Z|runtime|f7d0e997-9ea8-496a-8bcd-4567b12c4fbc]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 744, in persist
[MFLOG|0|2024-10-19T21:58:35.251597Z|runtime|2429c66b-946b-427e-a9ca-e1a1d5ea84b8]    self.save_artifacts(artifacts_iter(), len_hint=len(valid_artifacts))
[MFLOG|0|2024-10-19T21:58:35.251614Z|runtime|cd0a5815-da0d-421a-bfbb-ccb2b1f67563]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 31, in method
[MFLOG|0|2024-10-19T21:58:35.251633Z|runtime|5d2964dd-743a-4671-965e-725b9a270a40]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T21:58:35.251652Z|runtime|a3da250c-d2a1-4c46-9d73-39d6d1233003]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251669Z|runtime|d8e65521-e624-4ee7-ab67-c3413ada6319]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 45, in method
[MFLOG|0|2024-10-19T21:58:35.251685Z|runtime|b7ad230e-72e4-4ade-970c-a13cc5acb7ba]    return f(self, args, kwargs)
[MFLOG|0|2024-10-19T21:58:35.251702Z|runtime|d9a826f4-6655-47d8-8bc8-73197ed476c5]           ^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251719Z|runtime|1c35486a-b7cd-4e5f-97e2-8bd0d0bf8301]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 329, in save_artifacts
[MFLOG|0|2024-10-19T21:58:35.251736Z|runtime|d4d8884d-709e-4a94-bb68-6c157c3cef79]    save_result = self._ca_store.save_blobs(pickle_iter(), len_hint=len_hint)
[MFLOG|0|2024-10-19T21:58:35.251805Z|runtime|aa234954-dece-476f-a8f3-24835bc5461e]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251824Z|runtime|76f6c940-9eef-41e9-b5a4-55bf5f33039a]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/content_addressed_store.py", line 100, in save_blobs
[MFLOG|0|2024-10-19T21:58:35.251841Z|runtime|f82d030d-e2c5-48fd-9586-5797053e2092]    self._storage_impl.save_bytes(packing_iter(), overwrite=True, len_hint=len_hint)
[MFLOG|0|2024-10-19T21:58:35.251858Z|runtime|1c09fc99-bd61-4154-9295-9a03242ec1c6]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/plugins/datastores/local_storage.py", line 107, in save_bytes
[MFLOG|0|2024-10-19T21:58:35.251875Z|runtime|3c0dae1f-4321-46ac-9f6c-e7421d2a0323]    for path, obj in path_and_bytes_iter:
[MFLOG|0|2024-10-19T21:58:35.251892Z|runtime|0f7cbe1a-bb3b-48a1-92f3-962c9b0babfc]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/content_addressed_store.py", line 78, in packing_iter
[MFLOG|0|2024-10-19T21:58:35.251909Z|runtime|37c2bde1-4e75-483d-8028-99816ba66e9f]    for blob in blob_iter:
[MFLOG|0|2024-10-19T21:58:35.251932Z|runtime|2648367b-4af1-4b14-9880-33e6a2be971b]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/metaflow/datastore/task_datastore.py", line 302, in pickle_iter
[MFLOG|0|2024-10-19T21:58:35.251949Z|runtime|0b45ee34-8a7f-4020-96f1-ecb06d41e9cc]    blob = pickle.dumps(obj, protocol=2)
[MFLOG|0|2024-10-19T21:58:35.251966Z|runtime|dff15d2e-f570-49eb-81c6-983f958f89b2]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.251986Z|runtime|4a086dd1-a340-4c8e-87ed-9d35480b1989]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/tensorflow/python/framework/ops.py", line 327, in __reduce__
[MFLOG|0|2024-10-19T21:58:35.252008Z|runtime|0dc05c40-8e4c-4f09-869c-c54463317cc1]    return convert_to_tensor, (self._numpy(),)
[MFLOG|0|2024-10-19T21:58:35.252025Z|runtime|469f1350-73cc-4ede-a677-a8fb44988c28]                               ^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.252103Z|runtime|f042c08b-df2b-4513-b915-34e5b881c951]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.11/site-packages/tensorflow/python/framework/ops.py", line 375, in _numpy
[MFLOG|0|2024-10-19T21:58:35.252130Z|runtime|71d87476-36c8-4829-a80e-7c8b6d2a8eab]    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
[MFLOG|0|2024-10-19T21:58:35.252146Z|runtime|5eaf7c20-7ed2-466e-8c4d-b02fc368d0ae]    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:58:35.252164Z|runtime|cbadb3bd-fa55-4e07-b3d8-a1b3c0c3bf69]tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot convert a Tensor of dtype variant to a NumPy array.
[MFLOG|0|2024-10-19T21:58:35.252181Z|runtime|c074995c-4971-4b3a-a40d-d8b483670f7b]
[MFLOG|0|2024-10-19T21:58:35.252693Z|runtime|143c81a8-8998-4ca6-b493-2cc6555fa0d5]Task failed.