[MFLOG|0|2024-10-19T21:40:46.945639Z|runtime|f4d06421-3a26-45c0-a9c4-786135bad33b]<flow MNISTFlow step train> failed:
[MFLOG|0|2024-10-19T21:40:46.949345Z|runtime|4bdb4e89-2815-45a5-bddc-1373112d2c14]    Internal error
[MFLOG|0|2024-10-19T21:40:46.950354Z|runtime|06e29b49-230c-4bda-96ae-24529b7530ff]Traceback (most recent call last):
[MFLOG|0|2024-10-19T21:40:46.950452Z|runtime|620e3856-b3bb-4082-ba2c-c7cc485f762b]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/cli.py", line 1139, in main
[MFLOG|0|2024-10-19T21:40:46.950499Z|runtime|95739220-5d75-4506-9f9e-52365d73f2c2]    start(auto_envvar_prefix="METAFLOW", obj=state)
[MFLOG|0|2024-10-19T21:40:46.950535Z|runtime|7a70b071-affc-4b8c-b582-2c81b18e7a38]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/tracing/__init__.py", line 27, in wrapper_func
[MFLOG|0|2024-10-19T21:40:46.950568Z|runtime|a2f66eb7-7217-4a81-9b3a-98bf2c143dcc]    return func(args, kwargs)
[MFLOG|0|2024-10-19T21:40:46.950595Z|runtime|8535d6fc-fab0-4a28-8374-9b1125a54aac]           ^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:40:46.950621Z|runtime|ae5581b3-a5f4-4727-adf9-54c8127aeba8]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 829, in __call__
[MFLOG|0|2024-10-19T21:40:46.950654Z|runtime|19aa6cd7-e8b2-4c75-abee-34da47448b7c]    return self.main(args, kwargs)
[MFLOG|0|2024-10-19T21:40:47.098244Z|runtime|9753cad8-8bd2-46d8-a817-97b9106511a4]           ^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:40:47.098438Z|runtime|5b2168e2-abe9-4a22-a456-cb8c70f1a52a]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 782, in main
[MFLOG|0|2024-10-19T21:40:47.098473Z|runtime|acfced65-9157-4f26-9c88-52720477737e]    rv = self.invoke(ctx)
[MFLOG|0|2024-10-19T21:40:47.098496Z|runtime|8a107adf-205a-4ecb-952f-7e0445679e1b]         ^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:40:47.098518Z|runtime|8b8ea609-2386-4ec8-bfc1-aa5c0b0fa9a9]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1259, in invoke
[MFLOG|0|2024-10-19T21:40:47.098539Z|runtime|1ad028c5-0635-40ee-be4c-7747643fefac]    return _process_result(sub_ctx.command.invoke(sub_ctx))
[MFLOG|0|2024-10-19T21:40:47.098563Z|runtime|848ec0cb-c251-4070-b36f-4898745276f5]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:40:47.098582Z|runtime|dc5acfd9-c8b7-4cc7-b3f9-db5376ee1d40]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 1066, in invoke
[MFLOG|0|2024-10-19T21:40:47.098602Z|runtime|56a05ddb-e72a-46ff-b959-1e695d638454]    return ctx.invoke(self.callback, ctx.params)
[MFLOG|0|2024-10-19T21:40:47.098622Z|runtime|7e5879e8-00ee-41f1-b466-4880f6234b8d]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:40:47.098649Z|runtime|0692045a-8577-4a7a-a685-25ae30dec245]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/core.py", line 610, in invoke
[MFLOG|0|2024-10-19T21:40:47.098674Z|runtime|1f879b2b-8e04-41c4-913e-f5b9ebcffe8a]    return callback(args, kwargs)
[MFLOG|0|2024-10-19T21:40:47.098694Z|runtime|af12d7a3-c0d3-4b59-8668-55ccd599ef1d]           ^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:40:47.098714Z|runtime|97b3ad30-0864-413f-856b-cf216c86e0de]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/_vendor/click/decorators.py", line 21, in new_func
[MFLOG|0|2024-10-19T21:40:47.098733Z|runtime|6dc56a7d-1978-4f66-a496-8d1778c269b0]    return f(get_current_context(), args, kwargs)
[MFLOG|0|2024-10-19T21:40:47.098752Z|runtime|4b8c749c-4238-4d16-a29e-dedd0bfdf630]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[MFLOG|0|2024-10-19T21:40:47.098771Z|runtime|03d5f3cf-49cf-430d-9f54-740884f47023]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/cli.py", line 469, in step
[MFLOG|0|2024-10-19T21:40:47.098790Z|runtime|0e72c395-f7d3-47ab-9223-2a5f2ab52333]    task.run_step(
[MFLOG|0|2024-10-19T21:40:47.098809Z|runtime|3cd5830c-e9e3-4a77-a94d-ef91658f3c70]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/task.py", line 657, in run_step
[MFLOG|0|2024-10-19T21:40:47.098828Z|runtime|01127b13-e1be-442c-b39f-44280b7f45a8]    self._exec_step_function(step_func)
[MFLOG|0|2024-10-19T21:40:47.098846Z|runtime|1ac34b57-4b96-4981-8fd5-5faaca7cc4f8]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/.venv/lib/python3.12/site-packages/metaflow/task.py", line 62, in _exec_step_function
[MFLOG|0|2024-10-19T21:40:47.098865Z|runtime|9f254621-18a5-487c-bab7-507527666b1a]    step_function()
[MFLOG|0|2024-10-19T21:40:47.098885Z|runtime|5ea19151-100a-4b82-88c6-1ed5d40ecb72]  File "/Users/xrhd/repos/xrhd/sandbox/1_projects/workflows/hello.py", line 74, in train
[MFLOG|0|2024-10-19T21:40:47.098904Z|runtime|17ed1bf6-d784-466f-8c95-139ac6da3818]    params = model.init(jax.random.PRNGKey(0), jnp.ones((1, 28  28)))
[MFLOG|0|2024-10-19T21:40:47.098922Z|runtime|bf4681d9-104f-461f-b543-b69c2f55cc2d]             ^^^^^^^^^^
[MFLOG|0|2024-10-19T21:40:47.098941Z|runtime|90c91f58-6b25-4cb6-bb46-31bb25f9b9e5]AttributeError: 'CNN' object has no attribute 'init'
[MFLOG|0|2024-10-19T21:40:47.098961Z|runtime|bbd3a8f1-544e-47fd-9199-47384e24f3a7]
[MFLOG|0|2024-10-19T21:40:47.099599Z|runtime|95e81ee9-6245-4766-b1f9-4b38d8e01244]Task failed.